FROM golang:1.26 AS builder

WORKDIR /app

COPY . .

WORKDIR /app/api

RUN go build -o api

FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/api/api .

COPY --from=builder /app/scripts ./scripts

EXPOSE 3000

CMD ["./api"]
