services:

  websocket:
    image: ghcr.io/ishaan-jindal/termchat/termchat-websocket:latest

    container_name: termchat-websocket

    env_file:
      - .env

    restart: unless-stopped

  api:
    image: ghcr.io/ishaan-jindal/termchat/termchat-api:latest

    container_name: termchat-api

    env_file:
      - .env

    restart: unless-stopped

    depends_on:
      - websocket

  caddy:
    image: caddy:latest

    container_name: termchat-caddy

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

    depends_on:
      - api
      - websocket

    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest

    container_name: termchat-watchtower

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - DOCKER_API_VERSION=1.41

    command: --interval 30

    restart: unless-stopped

